language: ruby
rvm:
        - 2.4.0
notifications:
        email: false
script: bundle exec rails test
after_success:
        - CODECLIMATE_REPO_TOKEN=763d8da993788e74dc49fca5e3c87231c60b836854c16b0d7d1fa5dba919e07e bundle exec codeclimate-test-reporter
env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install: 
        - sudo locale-gen --no-archive es_CO.UTF-8
        - sudo /etc/init.d/postgresql stop
        - sudo /etc/init.d/postgresql start 9.3
        - psql -c 'CREATE DATABASE sivel2sjrven_pru;' -U postgres
        - bundle install
        - cp db/structure.sql db/structure.sql.conlock
        - sed -e "s/SET lock_timeout = 0;//g" db/structure.sql.conlock >db/structure.sql
        - cp config/database.travis.yml config/database.yml
        - cp config/initializers/sip.rb.plantilla config/initializers/sip.rb
        - bundle exec rake db:setup
        - bundle exec rake sip:indices

