language: ruby
rvm:
        - 2.2
notifications:
        email: false
script: CODECLIMATE_REPO_TOKEN=763d8da993788e74dc49fca5e3c87231c60b836854c16b0d7d1fa5dba919e07e xvfb-run rspec
env:
        global:
                - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_install: 
        - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
        - sudo apt-get update
        - sudo apt-get install libqt5webkit5-dev qtdeclarative5-dev qtlocation5-dev qtsensors5-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev qt4-default
        - sudo locale-gen --no-archive es_CO.UTF-8
        - psql -c 'CREATE DATABASE sivel2sjrven_pru;' -U postgres
        - bundle install
        - cp db/structure.sql db/structure.sql.conlock
        - sed -e "s/SET lock_timeout = 0;//g" db/structure.sql.conlock >db/structure.sql
        - cp config/database.travis.yml config/database.yml
        - rake db:setup
        - rake sip:indices

